### ISSUE TITLE
suggestion: show more headers

### ISSUE THREAD

**Issue by if1live** [ErnSur/Unity-Http-Debugger#24]
![image](https://user-images.githubusercontent.com/971476/200116087-a76318d7-964a-491a-bf20-bd8930ef03e9.png)
date, expires, last-modified, authorization custom header, ... more headers are more useful.

request headers = req.Content.Headers + req.Headers
response headers = res.Content.Headers + res.Headers + res.TrailingHeaders

my code
https://github.com/5minlab/Unity-Http-Debugger/commit/18cc13161f96a7a12387641e223196ebe380628c
(I didn't know TrailingHeaders, so my code doesn't contain res.TrailingHeaders)

**Comment by ErnSur** [comment]
Added in 1.1.3
